# ============================================================
# FINAL APK BUILD COMMAND
# Flutter Clean Build for Production
# ============================================================

Write-Host "🔥 FINAL APK BUILD - Starting..." -ForegroundColor Green
Write-Host ""

$MOBILE_APP_PATH = "e:\SUNNY\Jewel\APPERTMENT SOFTWER\LIFEASY_V27\mobile_app"

Set-Location $MOBILE_APP_PATH

# ============================================================
# STEP 1: Flutter Clean
# ============================================================
Write-Host "🧹 STEP 1: Running flutter clean..." -ForegroundColor Cyan
flutter clean

if ($LASTEXITCODE -ne 0) {
    Write-Host "❌ Flutter clean failed!" -ForegroundColor Red
    exit 1
}
Write-Host "✅ Flutter clean completed" -ForegroundColor Green
Write-Host ""

# ============================================================
# STEP 2: Flutter Pub Get
# ============================================================
Write-Host "📦 STEP 2: Running flutter pub get..." -ForegroundColor Cyan
flutter pub get

if ($LASTEXITCODE -ne 0) {
    Write-Host "❌ Flutter pub get failed!" -ForegroundColor Red
    exit 1
}
Write-Host "✅ Flutter pub get completed" -ForegroundColor Green
Write-Host ""

# ============================================================
# STEP 3: Build APK (Release Mode)
# ============================================================
Write-Host "🏗️  STEP 3: Building APK (Release mode, no shrink)..." -ForegroundColor Cyan
Write-Host "This may take 5-10 minutes..." -ForegroundColor Yellow
Write-Host ""

flutter build apk --release --no-shrink

if ($LASTEXITCODE -ne 0) {
    Write-Host "❌ APK build failed!" -ForegroundColor Red
    Write-Host "`n💡 Try this fix:" -ForegroundColor Yellow
    Write-Host "   flutter build apk --release --shrink" -ForegroundColor White
    exit 1
}

Write-Host "✅ APK build completed successfully!" -ForegroundColor Green
Write-Host ""

# ============================================================
# STEP 4: Show APK Location
# ============================================================
Write-Host "📍 APK Location:" -ForegroundColor Cyan
Write-Host "$MOBILE_APP_PATH\build\app\outputs\flutter-apu\app-release.apk" -ForegroundColor Green
Write-Host ""

# ============================================================
# STEP 5: Create Build Report
# ============================================================
$BUILD_DATE = Get-Date -Format "yyyy-MM-dd HH:mm:ss"

$REPORT = @"
# ✅ APK BUILD SUCCESS COMPLETE

## Build Information
- **Date**: $BUILD_DATE
- **Build Type**: Release (No Shrink)
- **Status**: ✅ SUCCESS

## APK Location
```
$MOBILE_APP_PATH\build\app\outputs\flutter-apk\app-release.apk
```

## Next Steps
1. ✅ Test the APK on a real device
2. ✅ Upload to Google Play Console (if needed)
3. ✅ Share with users

## Build Commands Used
`````bash
flutter clean
flutter pub get
flutter build apk --release --no-shrink
`````

## File Size
"@

# Get APK size if it exists
$APK_PATH = Join-Path $MOBILE_APP_PATH "build\app\outputs\flutter-apk\app-release.apk"
if (Test-Path $APK_PATH) {
    $APK_SIZE = (Get-Item $APK_PATH).Length / 1MB
    $REPORT += "`n- **APK Size**: $([math]::Round($APK_SIZE, 2)) MB`n"
}

$REPORT += @"

---
*Generated by FINAL_APK_BUILD.ps1*
"@

Set-Content -Path "$MOBILE_APP_PATH\..\APK_BUILD_SUCCESS_FINAL.md" -Value $REPORT -Encoding UTF8

Write-Host "📄 Build report created: APK_BUILD_SUCCESS_FINAL.md" -ForegroundColor Green
Write-Host ""
Write-Host "🎉 APK BUILD COMPLETE!" -ForegroundColor Green
Write-Host ""
Write-Host "📍 APK file location:" -ForegroundColor Yellow
Write-Host "   $APK_PATH" -ForegroundColor Green
Write-Host ""
Write-Host "💡 To install on device:" -ForegroundColor Yellow
Write-Host "   adb install $APK_PATH" -ForegroundColor White
Write-Host ""
